name: 'client'
version: 0.2.0
description: A simple rich content instant message platform.
authors:
  - Zac Falkner <falkzach@gmail.com>
  - Ben Campbell <benji@benjica.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  angular: '^1.1.2+2'
  bootstrap: "^3.3.4"
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'
  markdown: '^0.9.0'
  web_components: '^0.12.0+3'

dev_dependencies:
  mockito: '^0.11.0'
  test: any

transformers:
- dart_to_js_script_rewriter
- angular
