name: 'client'
version: 0.0.1
description: An absolute bare-bones web app.
authors:
  - Zac Falkner <falkzach@gmail.com>
  - Ben Campbell <benji@benjica.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'

dev_dependencies:
  test: any

transformers:
- dart_to_js_script_rewriter
